services:
  angular:
    image: node:20
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/SambaWeb-Front
      - .docker/:/SambaWeb-Front/.docker
    working_dir: /SambaWeb-Front
    command: bash -c "sh .docker/entrypoint.sh"
    networks:
      - sambaweb
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  sambaweb:
    external: true
